# Use the official Ubuntu image as a base
FROM debian:bookworm

# Set environment variables to avoid prompts during package installation
ENV DEBIAN_FRONTEND=noninteractive

# Update the package list and install Python and venv
RUN apt update && apt install -y \
    build-essential \
    libprotobuf-dev \
    protobuf-compiler \
    cmake \
    pkg-config \
    python3 \
    python3-venv \
    python3-pip \
    python3-dev \
    iperf3 \
    net-tools \
    iputils-ping \
    iproute2 \
    nano \
    curl \
    ethtool \
    sed \
    tcpdump \
    && rm -rf /var/lib/apt/lists/*

RUN apt clean
# Set the working directory inside the container
WORKDIR /app
# Copy the requirements file into the container
COPY requirements.txt .
# Create a virtual environment and install dependencies
RUN python3 -m venv venv && \
    ./venv/bin/pip install --upgrade pip setuptools wheel && \
    ./venv/bin/pip install -r requirements.txt

COPY network_stats.sh .
COPY traffic_monitor.py .

RUN sed -i '4i import os' venv/bin/flwr-serverapp
RUN sed -i 's/sys.exit(flwr_serverapp())/flwr_serverapp()/g' venv/bin/flwr-serverapp
RUN sed -i '/flwr_serverapp()/a \ \ \ \ os._exit(0)' venv/bin/flwr-serverapp

CMD ["/bin/bash"]
