[topology]
topo-type="gabriel"
topo-size=15
topo-variation=9
clients-number=10
switch-exclude=0.2
enable-bg-traffic=true
stp=false

[topology.links]
link-bw=100 # in Mbps
link-delay="2ms"
link-max-queue-size=1000 # in packet

[bg-traffic]
rate-std=20
switch-time-mean=20
switch-time-std=5
concurrent-tcp=1
max-rate=100

[docker-client]
mem-limit="1.5g"
memswap-limit="3g"
cpu-limit=0.7
fl-imgname="fl_mininet_image:latest"
bg-imgname="bg_mininet_image:latest"
data-mount="/home/osama/FederatedLearning/data" # absolute path
logs-mount="/home/osama/FederatedLearning/logs" # absolute path

[sdn-controller]
enable=true
ip=""
port=6653

[other]
name=""
logs-path="logs" # relative path
