[topology]
topo-type="gabriel"
topo-size=15
topo-variation=9
clients-number=5
switch-exclude=0.2
enable-bg-traffic=false
stp=true

[topology.links]
link-bw=100 # in Mbps
link-delay="2ms"
link-max-queue-size=1000 # in packet

[bg-traffic]
rate-std=10
switch-time-mean=10
switch-time-std=3
concurrent-tcp=1
max-rate=90

[docker-client]
mem-limit="1.5g"
memswap-limit="3g"
cpu-limit=0.7
fl-imgname="fl_mininet_image:latest"
bg-imgname="bg_mininet_image:latest"
data-mount="/home/osama/FederatedLearning/data" # absolute path
logs-mount="/home/osama/FederatedLearning/logs" # absolute path

[sdn-controller]
enable=false
ip="11.66.33.46"
port=6653

[other]
name="local"
logs-path="logs" # relative path
